vich_uploader:
    db_driver: orm

    mappings:
        destination_image:
            uri_prefix: /uploads/destinations
            upload_destination: '%kernel.project_dir%/public/uploads/destinations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
